### ISSUE TITLE
Rails 6.0.0 deprecation for the Shop model initializer

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#812] opened 2019-10-31 16:53 UTC
The deprecation notice is long, and the recommended reading on the why is not too enlightening. Is there a quick fix for this? From the initializer shopify_app.rb

     config.session_repository = Shop

DEPRECATION WARNING: Initialization autoloaded the constant Shop.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shop, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /Users/dlazar/Documents/Workspace/Apps/shinesty/config/environment.rb:5)
DEPRECATION WARNING: Initialization autoloaded the constant Shop.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shop, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.

**Comment by tanema** [comment] 2019-10-31 16:56
Yeah if you want to get rid of the deprecation notice, the best thing to do would be to require your shop model file directly so that you load it before that line in your config

**Comment by resistorsoftware** [comment] 2019-10-31 17:09
Sorry I don't follow. What does it mean to require a model before an initializer references it? 

I come from Sinatra world, so the quick and dirty isms of Rails are not something I grok as much as you do.

**Comment by resistorsoftware** [comment] 2019-10-31 18:01
Is that as simple as just saying 

     require 'shop'

in the initializer?

**Comment by tanema** [comment] 2019-10-31 18:13
Yeah what I was thinking `require 'shop'` however that might end up autoloading other things, so it might not get rid of your warning.

I will make a note to possibly run the config block after app initialization so that this no longer happen.

**Comment by resistorsoftware** [comment] 2019-10-31 18:21
Super! It seems like I have no patience for some of these matters. I read and re-read that document 10x and still came away with no real plan as to how to ensure my initializers are clean and re-loadable.

**Comment by axlekb** [comment] 2019-12-17 01:45
This appears to be a duplicate of https://github.com/Shopify/shopify_app/issues/757

**Comment by resistorsoftware** [comment] 2019-12-17 01:58
I would be happy to see it condensed down to one closed issue... no one in the crowd seems to enamoured to just fix it. Me included.

**Comment by shawnfrench** [comment] 2019-12-18 19:59
@resistorsoftware https://github.com/Shopify/shopify_app/pull/841 I believe you can fix this issue in your app following the instructions there, since afaict there is no code fix we can make in the gem, must be done in your initializer.

**Comment by axlekb** [comment] 2019-12-18 20:05
The included generators still insert a change that will be deprecated:

```ruby
 def update_shopify_app_initializer
    gsub_file 'config/initializers/shopify_app.rb', 'ShopifyApp::InMemorySessionStore', 'Shop'
 end
```

**Comment by shawnfrench** [comment] 2019-12-18 20:13
I believe that code is fine since I've [updated the generator](https://github.com/Shopify/shopify_app/blob/9e45f8fb2abbfcdf1117391c0ffe5f9ac6567531/lib/generators/shopify_app/install/templates/shopify_app.rb#L1) for `config/initializers/shopify_app.rb` so that if that gsub is run on any newly generated initializers, it will just change the class name within the `configure` block, that is within the `Rails.application.config.to_prepare` block, avoiding the deprecation warning.

**Comment by axlekb** [comment] 2019-12-18 20:20
Apologies!  I had missed the reference your mention in #841 (I saw your comment via email and was confused by your "there").  I did not see that the config was newly wrapped in a`Rails.application.config.to_prepare do` block.  Will give it a try.  Thanks!

**Comment by shawnfrench** [comment] 2019-12-20 02:56
Going to close this one as a duplicate and keep the first report (https://github.com/Shopify/shopify_app/issues/757) open. 

Note that the PR I referenced needs work, and there are a couple ideas, but in the mean time I've described the workaround here: https://github.com/Shopify/shopify_app/issues/757#issuecomment-567765898

**Closed by shawnfrench** 2019-12-20 02:56 UTC
Labels: rails6
