### ISSUE TITLE
Webhook Registrations Address/Path Inconsistent with Shopify API Gem 

### ISSUE THREAD

**Issue by kcamcam** [Shopify/shopify_app#1414] opened 2022-04-14 20:11 UTC
### Description

There is an inconsistency between the Shopify App gem's webhook registration attributes and that of the Shopify API gem. Since webhook registration is implicitly using the Shopify API context `host_name` as the URL combined with the Shopify Apps configured webhook address instead of the webhook address alone. If I'm not mistaken this is new to `v19`.

The trace can be followed in order:
- [shopify_app/managers/webhooks_manager.rb](https://github.com/Shopify/shopify_app/blob/48f3e36658a224951fabbf7b2c898b5c7b33b511/lib/shopify_app/managers/webhooks_manager.rb#L42)
- [shopify_api/webhooks/registry.rb](https://github.com/Shopify/shopify_api/blob/main/lib/shopify_api/webhooks/registry.rb#L29) 
- [shopify_api/webhooks/registrations/http.rb](https://github.com/Shopify/shopify_api/blob/afc2565f346cb15499293a017846b40f06e8b32f/lib/shopify_api/webhooks/registrations/http.rb#L12)

### Steps to Reproduce

1. Configure the the shopify app initializer.
    ```ruby
    # config/initializers/shopify_app.rb
    ShopifyApp.configure do |config|
      ...
      config.webhooks = [{ topic: 'orders/create', address: 'https://test.com/webhooks/orders_create' }]
    end
    ...
    ShopifyAPI::Context.setup(host_name: 'example.com', ...)
    ```
4. Authenticate the app in order to register the webhook

**Expected behavior:**

A webhook is created at "https://test.com/webhooks/orders_create" i.e. `"#{webhook.address}"`

**Actual behavior:**

A webhook is created as "https://example.com/https://test.com/webhooks/orders_create" i.e. `"https://#{context.host}/#{webook.address"}`

**Reproduces how often:**

Every time

### Browsers

Firefox Developer 100.0b5 (64-bit)

### Gem versions

- Shopify App `v19.0.1`
- Shopify API `v10.0.2`

### Suggested Fix
- Rename `ShopifyApp.configure.webhooks.address` to `ShopifyApp.configure.webhooks.path`
- Or, update the Shopify API gem to use the Shopify App gem's `address` instead of Shopify API gem's `host_name`.

**Comment by redareda9** [comment] 2022-05-26 10:13
Not fixed over a month later. 
I'm having the same problem. 
Did @shopify-admins gave up this repo as well?

**Comment by nelsonwittwer** [comment] 2022-08-29 15:03
@kcamcam / @redareda9 / @gtyanchev 

Apologizes for the delay in getting to this. I've merged a [PR that will address](https://github.com/Shopify/shopify_app/pull/1492) this regression. The conversion to paths vs addresses was certainly an oversight and we apologize for any inconvenience.

The maintenance of this gem has been assigned to a new team due to the slow responses that you have noticed. Thanks for your patience as me and my other new maintainers clear out the backlog here.

**Closed by nelsonwittwer** 2022-08-29 15:03 UTC
Labels: bug, webhooks
