### ISSUE TITLE
Generate Issue

### ISSUE THREAD

**Issue by QuantumLeaper** [Shopify/shopify_app#347] opened 2016-10-05 20:53 UTC
I'm new to this and am not too sure if this is a rails issue, or a Shopify issue. Using https://vimeo.com/130247240
 Anyhow, I cannot generate the necessary Shopify files utilizing:
`rails generate shopify_api --api_key=<KEY> --secret=<SECRET>`
After executing that I end up with:

```

/var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:89:in `<class:Response>': undefined method `cache_control' for class `ActionDispatch::Response' (NameError)
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:35:in `<module:ActionDispatch>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/http/response.rb:6:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/live.rb:1:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/live.rb:1:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller.rb:4:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller.rb:4:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/railtie.rb:2:in `require'
    from /var/lib/gems/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/railtie.rb:2:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:9:in `require'
    from /var/lib/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railtie.rb:9:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:14:in `require'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:14:in `block in <top (required)>'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:12:in `each'
    from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/all.rb:12:in `<top (required)>'
    from /root/Dev/backorderpro/config/application.rb:3:in `require'
    from /root/Dev/backorderpro/config/application.rb:3:in `<top (required)>'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `require'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:82:in `preload'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:143:in `serve'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
    from /var/lib/gems/2.3.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

**Comment by alanhill** [comment] 2016-10-05 21:14
You'll want to run `rails generate shopify_app --api_key <KEY> --secret <SECRET>`.
 `shopify_app` vs. `shopify_api`.

I can run the command without any issues for Rails 5 so this leads me to believe there's an issue elsewhere in your app.

**Comment by alanhill** [comment] 2016-10-05 21:15
Do you have any other info that leads you to believe there's a bug in the Gem?

**Comment by alanhill** [comment] 2016-10-05 21:23
Also looking at the stack trace it looks like it's pointing to line 3 of application.rb which in a freshly generated rails application using rails 5 is `require 'rails/all'`. 

It seems like the issue is isolated to your apps set up - going to close this issue. Feel free to re-open if you have any evidence suggesting otherwise!

I'd also recommend our [API forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) as they are a good place to get assistance from other partners/developers.

**Closed by alanhill** 2016-10-05 21:23 UTC
