### ISSUE TITLE
rails generate shopify_app fails in Rails 6.0.2.rc1

### ISSUE THREAD

**Issue by forsbergplustwo** [Shopify/shopify_app#830] opened 2019-11-29 10:42 UTC
Hey team,

Spinning up a brand new Rails 6.0.2.rc1 app and running the shopify_app generator fails. 

My setup:

```
ruby '2.6.5'
rails '6.0.2.rc1'
shopify_app '11.3.2' <-- only "custom gem" added to new rails app
```

As soon as I run `rails generate shopify_app` I get the following stacktrace:

```
/Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:353:in `add_controller_module': undefined method `start_with?' for :sessions:Symbol (NoMethodError)
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:260:in `normalize_options!'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:131:in `initialize'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `new'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:83:in `build'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1956:in `add_route'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1928:in `decomposed_match'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1892:in `block in map_match'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `each'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1886:in `map_match'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:1633:in `match'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:751:in `map_method'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:712:in `get'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/shopify_app-11.3.2/config/routes.rb:3:in `block (2 levels) in <main>'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:902:in `controller'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/shopify_app-11.3.2/config/routes.rb:2:in `block in <main>'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `instance_exec'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:649:in `block in with_default_scope'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:887:in `scope'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/mapper.rb:648:in `with_default_scope'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.rc1/lib/action_dispatch/routing/route_set.rb:411:in `draw'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/shopify_app-11.3.2/config/routes.rb:1:in `<main>'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `each'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:20:in `reload!'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/routes_reloader.rb:10:in `execute'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application/finisher.rb:184:in `block in <module:Finisher>'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:32:in `run'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.rc1/lib/rails/application.rb:363:in `initialize!'
	from /Users/FORSBERGtwo/app_bridge/config/environment.rb:5:in `<main>'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/zeitwerk-2.2.1/lib/zeitwerk/kernel.rb:23:in `require'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `block in require'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.rc1/lib/active_support/dependencies.rb:325:in `require'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /Users/FORSBERGtwo/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/FORSBERGtwo/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

If I downgrade to rails 6.0.1 and re-run the `rails generate shopify_app` command, everything works fine.

Not sure if this should be posted on the rails issues page or here, but I thought I'd start with the gem repo.

Thanks!
Bjorn

**Comment by tolgap** [comment] 2019-12-12 16:47
@forsbergplustwo https://github.com/rails/rails/commit/6629ed7a5e2aaeb21a5a25ceeeb1e98aa77f1598

It's a regression in Rails. Already merged into the `6-0-2` branch. It looks like `6.0.2-rc2` has been released as well that contains the fix: https://github.com/rails/rails/releases/tag/v6.0.2.rc2

**Closed** 2019-12-17 15:40 UTC
