### ISSUE TITLE
Using nested route throws routing exception on install

### ISSUE THREAD

**Issue by cerveny** [Shopify/shopify_app#603] opened 2018-06-19 04:20 UTC
I am using Rails 5.2.0, shopify_app gem 8.2.6 a shopify_api gem 4.11.0. I created bare shopify application. Then I added configuration for nested route as outlined in Nested Route section of Mounting the Engine.

When I start server and visit "localhost:3000/nested" I am redirected to login page at "localhost:3000/nested/login". After I enter development store name and hit install, I am redirected to "localhost:3000/nestedauth/shopify" which throws "No route matches [GET] "/nestedauth/shopify"" and instalation stops. 

![shopify-nested-route-exception](https://user-images.githubusercontent.com/5987984/41576349-37e9903c-7387-11e8-86f5-afcf00a755af.png)

My routes.rb look like this
```
Rails.application.routes.draw do
  scope '/nested' do
    root :to => 'home#index'
  end
  mount ShopifyApp::Engine, at: '/nested'
end
```

My shopify_app.rb
```
ShopifyApp.configure do |config|
  config.root_url = '/nested'
  config.application_name = "My Shopify App"
  config.api_key = ...rest as generated by generator
```
  
My omniauth.rb
```
  Rails.application.config.middleware.use OmniAuth::Builder do
    provider :shopify,
            callback_path: '/nested/auth/shopify/callback',
             ShopifyApp.configuration.api_key ...rest as generated by generator
```

**Comment by juan267** [comment] 2018-08-24 08:27
I'm experiencing the same problem, any updates on this?

**Comment by Shine18** [comment] 2019-01-15 23:16
Any update on this?

**Comment by ragalie** [comment] 2019-01-16 14:07
Are you experiencing the behaviour with 8.4.0? The logic has changed considerably from 8.2.6 and may be resolved at this point.

**Comment by Shine18** [comment] 2019-01-18 06:15
I added a route '/shopify' in my routes files. and pointed it to the index of app's home controller. That's how i fixed it.

**Comment by andreas-sotnik-2k19** [comment] 2019-04-06 14:54
I have the same issue on 8.6.0 version...

I think the issue may be caused by `authenticate_in_context` method of `ShopifyApp::SessionsController`:

```
def authenticate_in_context
     redirect_to "#{main_app.root_path}auth/shopify"
end
```

It takes root_path of the app without taking nesting into consideration...


I'm trying to do a local patch like this:

```
ShopifyApp::SessionsController.class_eval do
  def authenticate_in_context
    redirect_to "#{ShopifyApp.configuration.root_url}/auth/shopify"
  end
end
```

This fixes the url, but still there is no route for `/app/auth/shopify`...

**Comment by manuca** [comment] 2019-05-21 18:34
This is still an issue in the current `master` branch. It seems to be exactly as described above.

**Comment by mkevinosullivan** [comment] 2020-03-05 21:35
@manuca @andreas-sotnik-2k19 I've tried to replicate this issue with a recent version of the gem (v12.0.4) and am unable to do so.  What are the steps to replicate, or if you've tried it with a recent version, does it still occur?

**Comment by codemicky** [comment] 2020-03-30 08:07
@andreas-sotnik-2k19 I think your local path also should help me to fix my issue.
But it looks a stupid question, in which file have you added that code?

```
ShopifyApp::SessionsController.class_eval do
  def authenticate_in_context
    redirect_to "#{ShopifyApp.configuration.root_url}/auth/shopify"
  end
end
```

**Comment by andreas-sotnik-2k19** [comment] 2020-03-30 13:09
@codemicky Sorry, I don't really remember where to put it... I guess `application.rb` may be the place.
I just migrated all of my projects to Rails 6.x (with the latest version of `shopify_app` gem) and everything works just fine without this code.

**Comment by manuca** [comment] 2021-02-26 13:36
It seems my issue was related to Devise + omniauthable setting, not a problem with nesting routes itself. I can't confirm this 100% at this moment but I'm pretty sure that was the problem back then. I leave this as a lead in case someone wants to explore this possibility, also this article is related and proved usesful
https://www.botreetechnologies.com/blog/how-to-fix-no-route-matches-get-auth-shopify-after-introducing-devise-with-omniauth/

**Comment by andyw8** [comment] 2021-02-26 14:36
@manuca Good to hear you have it working, and thanks for sharing the solution.

As this ticket was originally created for a much older version of the gem (from 2018), I think it's best to close this, and for anyone who runs into similar problems to open a new ticket.

**Closed by andyw8** 2021-02-26 14:36 UTC
Labels: Bug, auth

**Comment by sshaw** [comment] 2021-04-17 22:51
I upgraded from `7.2.7` to `9.0.4` and in production my app is served on a subpath via NGINX + Passenger. 

To prevent login and webhook delivery issues I had to set the following in `config/initializers/shopify_app.rb`: 

```rb
if Rails.env.production?
  config.login_url = "/subpath/login"
  config.root_url = "/subpath"
end
```

I had tried a variety of combinations that also included mounting the engine at the subpath but the above is the only thing that fixed both issues.
