### ISSUE TITLE
Chrome 80 issue with JWT

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1306] opened 2021-08-12 21:44 UTC
Within the last 2 weeks, when customers install our apps (all have been using JWT for months), they are seeing this error in the Shopify Apps within the store

<img width="1052" alt="app issue" src="https://user-images.githubusercontent.com/1209073/129273989-2a0c770b-4a0b-49f4-a117-04d3c9828e46.png">

We use the latest shopify_app 18.0.2 with JWT.

**Comment by nelsonwittwer** [comment] 2022-09-19 20:43
We've been unable to reproduce this issue as well. I'm going to close this, but if you still see issues feel free to reopen.

**Closed by nelsonwittwer** 2022-09-19 20:43 UTC
Labels: bug
