### ISSUE TITLE
Webhook generator incorrectly inserts webhooks into config.rb

### ISSUE THREAD

**Issue by Dragas** [Shopify/shopify_app#427] opened 2017-07-06 09:10 UTC
Right now, the webhook generator looks for "end" string or `config.webhooks` literal. The problem with the former is that it replaces ALL instances of `end` with `config.webhooks` literal. For example the following:
```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = ENV["API_KEY"]
  config.secret = ENV["SECRET"]
  config.scope = "read_orders, write_orders, read_products, write_products, read_themes, write_themes,
 read_script_tags, write_script_tags"
  config.assets = [
      {key: "snippets/snippet-liquid.liquid", value: 'app/assets/liquid/liquid.liquid'},
      {key: "snippets/snippet-calendar.liquid", value: "app/assets/liquid/snippet-calendar.liquid"}
  ]
  config.embedded_app = true
end
```
After running `add_webhooks -t foo -a bar` results in

```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = ENV["API_KEY"]
  config.secret = ENV["SECRET"]
  config.scope = "read_orders, write_orders, read_products, write_products, read_themes, write_themes,
 read_script_tags, write_script_tags"
  config.embedded_app = true
  config.assets = [
      {key: "snippets/snippet-liquid.liquid", value: 'app/assets/liquid/liquid.liquid'},
      {key: "snippets/snippet-cal  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
endar.liquid", value: "app/assets/liquid/snippet-cal  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
endar.liquid"}
  ]
  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
end
```

Instead, the generator should remove the last `end` instance in the file (or `}` if a different style is used)

**Comment by kevinhughes27** [comment] 2017-07-06 14:38
Nice find!

**Comment by alanhill** [comment] 2017-07-07 01:29
@Dragas how can I replicate this? I tried but `assets` isn't a valid config, so it's not able to generate the webhook. 

Given a `config/initializers/shopify_app.rb` file of:

```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = "<api_key>"
  config.secret = "<secret>"
  config.scope = "read_orders, read_products"
  config.embedded_app = true
  config.assets = [
      {key: "somekey", value: 'somevalue'},
      {key: "someotherkey", value: "someothervalue"}
  ]
end
```

If I run `rails g shopify_app:add_webhook -t foo -a bar` I get:

```
config/initializers/shopify_app.rb:7:in `block in <top (required)>': undefined method `assets=' for #<ShopifyApp::Configuration:0x007f9c89c2d350> (NoMethodError)
```

**Comment by alanhill** [comment] 2017-07-07 01:36
Ahh I see, in relation to #390

**Comment by alanhill** [comment] 2017-07-07 03:00
The fix for this is pretty easy, but a regression test would be strange as it would need an invalid config file.

**Comment by Dragas** [comment] 2017-07-07 06:15
You can remove the additional invalid fields as they do not have any useful
effect unless you use the hack provided in #390 to extend
`ShopifyApp.Configuration`. The same issue can be replicated if you provide
valid app name that contains `end` or write it in permissions string.

**Comment by Dragas** [comment] 2017-07-07 07:02
For example:
```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App is ending"
  config.api_key = ENV["API_KEY"]
  config.secret = ENV["SECRET"]
  config.scope = "read_orders, write_orders, read_products, write_products, read_themes, write_themes,
 read_script_tags, write_script_tags"
  config.embedded_app = true
  config.scripttags = [
      {event: "onload", src: "https://5560bc74.ngrok.io/calendar.js", display_scope: "all"}
  ]
end
```
After running `rails g -t foo -a bar` results in
```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App is   config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
ending"
  config.api_key = ENV["API_KEY"]
  config.secret = ENV["SECRET"]
  config.scope = "read_orders, write_orders, read_products, write_products, read_themes, write_themes,
 read_script_tags, write_script_tags"
  config.embedded_app = true
  config.scripttags = [
      {event: "onload", src: "https://5560bc74.ngrok.io/cal  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
endar.js", display_scope: "all"}
  ]
  config.metafields = [
      {namespace: "attributes", key: "local_delivery_request", value_type: "string", value: ""}
  ]

  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
end
```

**Comment by kevinhughes27** [comment] 2017-10-03 15:27
so the issue is that you had the word `end` in calendar? @alanhill can you open a new issue that just describes how the Webhook generator is fragile if content includes the word `end`

**Closed by kevinhughes27** 2017-10-03 15:27 UTC
